### ISSUE TITLE
test dependencies listed as dependencies

### ISSUE THREAD

**Issue by n8han** [softprops/ls#10]
I think these should just be excluded, but it's your call!

**Comment by softprops** [comment]
good call I'll add that to the list for tonight.  There's kinda support for something light that now called [dependencyFilter](https://github.com/softprops/ls/blob/master/plugin/src/main/scala/ls.scala#L26) which filters out unwanted dependencies like [scala std lib](https://github.com/softprops/ls/blob/master/plugin/src/main/scala/ls.scala#L326).  ModuleId has an [optional config](https://github.com/harrah/xsbt/blob/0.11.0/ivy/IvyInterface.scala#L12) I could inspect and parse out test deps as part of the default filter.

**Comment by n8han** [comment]
I assumed they could be easily excluded by config but I don't really know.

Btw I just updated all the Uf module descriptions and lsync'd, but they 
are still the old names. It's being cached somewhere I guess?

**Comment by softprops** [comment]
Sounds like a bug in the update code. I'll make s separate issue. Thanks!
