### ISSUE TITLE
make sure that description fields are updated when syncing

### ISSUE THREAD

**Issue by softprops** [softprops/ls#11]
as well as other fields

**Comment by n8han** [comment]
The Docs link did add to an existing record, but maybe it's a problem 
with updating existing fields. I used Docs for 
http://unfiltered.databinder.net/ but is that really "homepage"? Is Docs 
for scaladocs?

**Comment by softprops** [comment]
Records ~should~ be unique on [name, org, user, repo](https://github.com/softprops/ls/blob/master/server/src/main/scala/Libraries.scala#L323-326) then the versions should be unique on [version](https://github.com/softprops/ls/blob/master/server/src/main/scala/Libraries.scala#L342-345) but there could be a bug in there.

**Comment by softprops** [comment]
I could see some cases were docs and homepage could be the same. Depending on what reference material you want users to reference your api. Since uf uses pamflet for docs that could be docs I guess.

**Comment by softprops** [comment]
re the homepage vs docs thing. the homepage is intended for something like a landing page for the library individual versions can have their own api docs which is why I have that separate.
