### ISSUE TITLE
"site" specified in json not shown after lsync

### ISSUE THREAD

**Issue by n8han** [softprops/ls#12]
Here we have a site property: https://github.com/unfiltered/unfiltered/blob/master/library/src/main/ls/0.5.1.json

Did `lsync`, but not showing at ls.implicit.ly: http://ls.implicit.ly/unfiltered/unfiltered#unfiltered

**Comment by softprops** [comment]
push fixes and some ui enhancements to heroku. I sync'd unfiltered and the project  page links show

```
curl -X POST 'http://ls.implicit.ly/api/libraries' -d 'user=unfiltered&repo=unfiltered&version=0.5.1'
```

**Comment by n8han** [comment]
Looks great, thanks Doug!
