### ISSUE TITLE
NoClassDefFoundError error when testing plugin through publish-local

### ISSUE THREAD

**Issue by n8han** [softprops/ls#2]
```
ls@0.1.0-SNAPSHOT > ls-find unf 
[error] {file:/home/nathan/Programming/ls/}ls/*:ls-find: java.lang.NoClassDefFoundError: ls/LibraryVersions
[error] Total time: 0 s, completed Nov 3, 2011 9:08:56 AM
```

This happens whether the plugin is added globally or to a single project. Confirmed on two separate Ubuntu 11.10 installations, cleaned out the ivy cache and various other things many times only to reach the same error.

However, when I configured as ProjectRef dependency to a local directory, it worked immediately. I wonder if this is the only way ls has been tested, so far? If you are unable to replicate, perhaps you can tell me which sbt command will print out the classpath that sbt is using when failing to find the the ls.LibraryVersions class. Then I can see what ls jar it's looking at, and peek inside to see if the class is there or not.

In any case, this makes me wonder if a git dependency is actually more stable than using a maven dependency, considering all the problems with resolution and corrupted caches that we are having lately. I tried this initially with posterous-sbt, but went with the binary maven dependencies as those seemed to be recommended. Now I'm inclined to revisit that. The other benefit is tat people can use it for versions of sbt you have not published artifacts for, such as prerelease versions. Of course, they can do that anyway, but it's easier if that is just how it always works.

**Comment by softprops** [comment]
providing some linkage here to document possibilities

This is probably related to a classloader issue I found with jerkson + sbt 
- [sbt post](http://groups.google.com/group/simple-build-tool/browse_thread/thread/9878b1dc2631f20/91dc24e42a5690ba?lnk=gst&q=access+to+case+class+%40ScalaSigs+%2F+class+loader+question#91dc24e42a5690ba)
- [jerkson gh issue](https://github.com/codahale/jerkson/issues/38)
- [current work around](https://github.com/softprops/ls/blob/master/plugin/src/main/scala/classloaders.scala)

**Comment by softprops** [comment]
not sure if f1aa815ba3a212fcdc725ddfb323770259f6bd9c was a fix or not but it may help

**Comment by n8han** [comment]
that did it

**Comment by softprops** [comment]
yay. I was worried about that
