### ISSUE TITLE
hitting enter in the search box considered harmful

### ISSUE THREAD

**Issue by softprops** [softprops/ls#22]
swallow submit events. who needs em!

**Comment by softprops** [comment]
fixed w/ 871ec7d38bd05fa942c5202a70847749646a9b2b

**Comment by ngocdaothanh** [comment]
Can you explain why it is harmful?
Thanks.

**Comment by softprops** [comment]
Haha, it's not actually `harmful`. That's just the way someone colorfully worded it on the list. Previously I just executed search queries asynchronously based on key events but was not handling the obvious form `submit` event that you get with a traditional html forms so if someone hit enter the form would submit and reload the page which was not the intended use. I changed to this to capture the `submit` event and without actually reloading the page or changing the browsers url. Hitting enter now just executes the same async search key events do.
