### ISSUE TITLE
gracefully handle potential http errors in lsinit

### ISSUE THREAD

**Issue by softprops** [softprops/ls#27]
Reported on the sbt list  by Heiko

I tried the conscripted lsinit, but I ran into an issue with project/plugins.sbt (the right name!):

addSbtPlugin("me.lessis" % "ls-sbt" % "Unexpected response code: 503
")

Then I ran lsinit a second time which added (!!):

resolvers ++= Seq(
  "less is" at "http://repo.lessis.me",
  "coda" at "http://repo.codahale.com")

addSbtPlugin("me.lessis" % "ls-sbt" % "0.1.0")

**Comment by softprops** [comment]
This potentially happened as I was pushing a heroku deploy

**Comment by n8han** [comment]
I don't understand all these exclamation points. Is project/plugins.sbt 
not the right name?

**Comment by softprops** [comment]
I think the context may have been lost in translation. I just copied it from the sbt list. I think I just need to capture http errors. It looks looks like here the server wasn't available, which is strange if it returned a 200 with that as a message body? In any case, its not the file that generated its the string that got put into the version val. Not a huge deal. I just looks like a timing issue with me running a heroku deploy with someone executing lsinit at the same time.

**Comment by n8han** [comment]
Yeah I can definitely improve the error handling; this was just a quick 
and dirty hack.

But I'm curious if there is something the matter with the 
project/plugins.sbt path. There seems to be a lot of different places 
sbt checks for plugin-project definitions and I'm not sure which is 
preferred.

**Comment by softprops** [comment]
We'll see if people complain I think this is fine for now for local plugins. I may actually try to factor some of the plugin appending code to support installing plugins. I know know that I can't actually share that code between modules until 0.11.2 :)

**Comment by n8han** [comment]
The "aggregate" project plugin may be of assistance with that, if it 
works with 0.11.1.

**Comment by softprops** [comment]
link to thread https://groups.google.com/group/simple-build-tool/browse_thread/thread/9634528dd464796e#

**Comment by n8han** [comment]
On 11/27/2011 08:34 PM, doug tangren wrote:

> link to thread https://groups.google.com/group/simple-build-tool/browse_thread/thread/9634528dd464796e#
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/softprops/ls/issues/27#issuecomment-2891736

This sort of thing would be nice to have in a library, too. If sbt were 
in ls, I could use ls to find the latest version of the launcher instead 
of having to release a new version of conscript every time sbt has a 
release.
