### ISSUE TITLE
doc launch

### ISSUE THREAD

**Issue by softprops** [softprops/ls#30]
Just an idea (just noting some random thoughts)

If you start playing with a library, the next most logical thing to do is to follow up on its documentation. It would be pretty convenient to be able to launch its docs right from sbt (windowing system permitting)

```
> ls-docs dynamic-json@0.1
```

Could launch the associated docs url for a library version falling back on the homepage is one is defined and finally falling back on the gh repo url.

You could probably take this idea even further in other directions

```
> ls-open-issue unfiltered@0.5.1
```

Could potentially open up the gh issue for a given repo and if gh issues uses query string params to fill in fields set a default issue title with the provided version, ect.

Before going to far on a tangent here, this could be fodder for a other plugins using the ls api instead of packing in too much functionality into one.

**Comment by regadas** [comment]
+1 on the ls-docs features the ls-open-issue I think it might come handy but users will eventually fallback to the gh UI
