### ISSUE TITLE
seq(lsSettings:_*) doesn't work with Windows

### ISSUE THREAD

**Issue by etorreborre** [softprops/ls#33]
I get this error when I reload my project definition:

 java.io.IOException: Cannot run program "git": CreateProcess error=2, The system cannot find the file specified

However when I type "git" on the command line in a DOS console, I have no errors.

....

After digging into [something similar](https://github.com/gseitz/sbt-release/issues/6), I found that the workaround works ok: "remove git.cmd" from the PATH.

I just leave this issue open so that others can troubleshoot their issues, while maybe you add a note for Windows users in the doc?

**Comment by softprops** [comment]
Thanks Eric. Someone ran into this and reported it in #32. I'll try to add better handling of error conditions here.

**Comment by softprops** [comment]
should be fixed now

**Comment by etorreborre** [comment]
Yes it works fine indeed.
