### ISSUE TITLE
Can't find a way to specify a http proxy

### ISSUE THREAD

**Issue by etorreborre** [softprops/ls#34]
For those of us behind firewalls, it would be very useful to be able to specify a proxy / user name / password to access the ls commands.

I've added those in the -Dhttp.proxyHost, , -Dhttp.proxyPort,-Dhttp.proxyUser,  -Dhttp.proxyPassword properties of by sbt launcher script but they don't seem to be used.

**Comment by softprops** [comment]
Ah, I should have seen this one coming. I'll have to read up on dispatch's client docs to see if there is extra configuration I need to do if these settings are present. Again, thanks for reporting the issue and trying out the plugin.

**Comment by etorreborre** [comment]
Closing this old issue now.
