### ISSUE TITLE
jerkson will not resolve without custom repo

### ISSUE THREAD

**Issue by n8han** [softprops/ls#4]
If ls plugin depends on jerkson then the instructions for installing it need to tell you to add a resolver for it as well:

```
resolvers += "coda" at "http://repo.codahale.com"
```

Otherwise, people who do not already have the artifact in their ivy cache will get an error when trying to use the plugin. (Repos are not transitive.)

**Comment by softprops** [comment]
Oh right. It ain't easy living on the outskirts of scala-tools!

It's a good thing I made external resolvers a [seq](https://github.com/softprops/ls/blob/master/plugin/src/main/scala/ls.scala#L328) I'll have to document adding your dependencies resolvers that aren't on scala-tools to that as well.

**Comment by n8han** [comment]
this looks fixed on the site
