### ISSUE TITLE
Error synchronizing project libraries Unexpected response code: 404

### ISSUE THREAD

**Issue by Sciss** [softprops/ls#47]
hey, I'm getting this error when running `lsync`:

```
[info] lsyncing project Sciss/sbt-appbundle@0.11...
[warn] Error synchronizing project libraries Unexpected response code: 404
```

this is my project: https://github.com/Sciss/sbt-appbundle

**Comment by softprops** [comment]
Looks like your default branch is `Work` and not `master`. This is a subtle thing I need to document better. In most cases the name of the branch people push code to on github is master, so it's the default.

Try adding the following to [build.sbt](https://github.com/Sciss/sbt-appbundle/blob/Work/build.sbt#L44-53)

```
(LsKeys.ghBranch in LsKeys.lsync) := Some("Work")
```

Let me know if that works so I can close this.

**Comment by Sciss** [comment]
Ah, ok, sorry I forgot about my branch. I merged it into master now, anyway. It works now, thanks!
