### ISSUE TITLE
`ls` fails to detect "sbt" in the project

### ISSUE THREAD

**Issue by alaz** [softprops/ls#48]
The generated JSON is [here](https://github.com/osinka/subset/blob/master/src/main/ls/0.6.4.json). As you may see `sbt` is equal to `false`.

That's pretty ridiculous actually: since the JSON is generated from SBT plugin, `sbt` is _supposed_ to be `true` :)

**Comment by softprops** [comment]
Um... I'll leave this issue unless I am misunderstanding you.

The project you want to publish is actually not a plugin. See the "Creating a Plugin" section of the [sbt wiki](https://github.com/harrah/xsbt/wiki/Plugins).

The first thing you have to do is to tell sbt your project is an sbt plugin with

```
sbtPlugin := true
```

There [not one line in your project](https://github.com/osinka/subset/search?q=sbtPlugin&choice=code&langOverride=&start=) that references that setting in your project so actually, the `sbt` property of your project is _supposed_ to be `false` :) I can give you a quick tip and add it [here](https://github.com/osinka/subset/blob/master/build.sbt) if you want sbt to treat your project as a plugin.

For a short description of the json properties listed in the `:version.json` file, check my own [documentation](http://ls.implicit.ly/#publishing)

I hope you don't think everything is _ridiculous_ before you understand the tool :)

fwiw, I'm not even sure you meant for this to be a plugin but instead a library which works fine through `ls` - https://gist.github.com/1694858

Please clarify your question.

**Comment by alaz** [comment]
Uh-oh, my bad! I've just been inattentive to the documentation at [ls.implicit.ly](http://ls.implicit.ly/#publishing) and simply didn't read that `sbt` in JSON means _plugin_ vs. _not a plugin_. Since my project is not a plugin, everything works as expected, so I'm closing the issue. Really sorry for wasting your time and many thanks for the detailed answer!

Regards,
Alexander

**Comment by softprops** [comment]
no worries. I wouldn't disagree that I could always to a better job with my own documentation :)
