### ISSUE TITLE
404 on lsync post

### ISSUE THREAD

**Issue by sirthias** [softprops/ls#49]
Just tried to `lsync` via ls 1.1.
The sbt console yields this error:

```
[warn] Error synchronizing project libraries Unexpected response code: 404
```

This is the HTTP conversation happening:

```
POST /api/1/libraries HTTP/1.1
Content-Length: 54
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Host: ls.implicit.ly
Connection: Keep-Alive

user=spray&repo=spray-json&branch=master&version=1.1.0

HTTP/1.1 404 Not Found
Server: Scala Netty Unfiltered Server
Content-Length: 0
Connection: keep-alive
```

Is the API down?

**Comment by Sciss** [comment]
Maybe you did the same mistake as I did: https://github.com/softprops/ls/issues/47

--> ls looks up the master branch, even if you set another one as default branch on github.

**Comment by sirthias** [comment]
Indeed, Sciss, this was the same problem.
I should have spent more time searching through the closed issues...

Still, maybe we can rededicate the issue to "Improve error message for wrong-branch lsync" ?

**Comment by softprops** [comment]
Great idea guys. Ill make an issue for this.
