### ISSUE TITLE
please publish ls-sbt plugin for sbt0.11.3

### ISSUE THREAD

**Issue by xuwei-k** [softprops/ls#59]

**Comment by softprops** [comment]
It should be published for 0.11.3 just under a different resolver. Starting with 0.11.3 and moving forward you should find it under the community plugins resolver host. Checkout [dispatch's plugin def](https://github.com/dispatch/dispatch/blob/master/project/plugins.sbt#L4) for an example.

**Comment by softprops** [comment]
I still have some refactoring for internal sbt changes made to the sbt 0.12.\* series but that should be wrapped up soon.

**Comment by xuwei-k** [comment]
>  It should be published for 0.11.3 just under a different resolver. 

Oh, I didn't know that. Thanks.

**Comment by softprops** [comment]
I'll update the readme tonight. Thanks!
