### ISSUE TITLE
getting a 404 error on lsync

### ISSUE THREAD

**Issue by freeeve** [softprops/ls#67]
Maybe this is temporary?

```
> lsync
[info] lsyncing project AnormCypher/AnormCypher@0.3.0...
[warn] Error synchronizing project libraries Unexpected response code: 404
[success] Total time: 0 s, completed Feb 19, 2013 8:45:41 PM
```

**Comment by softprops** [comment]
Ls looks version meta info under src/main/ls on github. It looks like you havent committed and  pushed it yet. https://github.com/AnormCypher/AnormCypher/tree/master/src/main

**Comment by freeeve** [comment]
cool, didn't realize that. sorry for bugging you!

**Comment by softprops** [comment]
no worries. the error message should probably be more informative. cool library by the way!

**Comment by Sciss** [comment]
I'm having trouble again with the error. Two projects: 

https://github.com/Sciss/SonogramOverview

```
[info] lsyncing project Sciss/SonogramOverview@1.4.0...
[warn] Error synchronizing project libraries Unexpected response code: 404
```

And

https://github.com/Sciss/Desktop

```
[info] lsyncing project Sciss/Desktop@0.2.0...
[warn] Error synchronizing project libraries Unexpected response code: 404
```

Both are on master as default branch and have the `.ls` files in the right place, as far as I can see.

**Comment by Sciss** [comment]
It seems generally not working at the moment? I get 404 for every project now it seems, even the 'old ones' that already have existing entries.

**Comment by softprops** [comment]
Looks like I'm finally starting to get rate limited by github. Sorry for this. I'll look into the issue.

**Comment by softprops** [comment]
can you give this another try, @n8han noticed this problem when lsyncing unfiltered yesterday. I was able to reproduce the problem then confirmed it didn't happen after a quick fix to the server. Can you try and again and let me know if you are experiencing the same issue?

**Comment by Sciss** [comment]
It seems to be working fine now, all went through. Thanks!
