### ISSUE TITLE
projects with lots of modules difficult to update

### ISSUE THREAD

**Issue by n8han** [softprops/ls#8]
With `ls-write-version` you get prompted for overwriting each module and you have to answer.

**Comment by softprops** [comment]
I could default to Y if you just hit `return`. I show the warning if the file exists in case they may have hand edited the versions file. I didn't was to override any of their changes before they know what happened, someone may get mad.

**Comment by n8han** [comment]
This is already fixed (by me). I'm not sure why github doesn't send an email when bugs change status; I was actually afraid to open an issue for that reason, I thought you might see the issue and start working on it.
